name: Java CI

on:
  push:
    branches:
      - '**'
    paths:
      - '**.gradle*'
      - '**.properties'
      - '**/src/**'
      - '.github/workflows/**'
    tags-ignore:
      - '*.*'
  pull_request:
    paths:
      - '**.gradle*'
      - '**.properties'
      - '**/src/**'
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build with JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'Masterzach32/artifactory' }}
    strategy:
      matrix:
        java: [ 16 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-jdk${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-jdk${{ matrix.java }}-gradle-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
  publish:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-jdk16-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-jdk16-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Build and Publish Artifacts
        run: ./gradlew -x test publish publishPlugins -Pgradle.publish.key=${{ secrets.gradle_publish_key }} -Pgradle.publish.secret=${{ secrets.gradle_publish_secret }} --no-daemon
        env:
          ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.maven_username }}
          ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.maven_password }}
